name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Hardanish-Singh
          template: classic
          
          # This creates the side-by-side layout (Radar on right)
          config_display: large
          
          # The activity graph
          base: activity
          
          # NOTABLE CONTRIBUTIONS SETTINGS
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_notable_indepth: yes
          plugin_notable_days: 3000
          # This line is REQUIRED to show the text list "Contributed to..."
          plugin_notable_repositories: yes 
          
          config_timezone: America/Toronto
